### ISSUE TITLE
autoinjector does not inject sidecar for pods in namespaces with istio-env set to default

### ISSUE THREAD

**Issue by jsPlachetka** [istio-ecosystem/istio-installer#4] opened 2019-03-15 12:55 UTC
The autoinjector does not inject a sidecar for pods in namespaces where the istio-env label is explicitly set to the default istio instance (enableNamespacesByDefault).
We discovered that the reason for this behaviour is, that the webhook does not listen for create actions with the according label, if it's the default istio instance (see [mutatingwebhook.yaml](https://github.com/c0d1ngm0nk3y/istio-installer/blob/0ab390bf8d41974eff85942e47e539f4a00e3521/istio-control/istio-autoinject/templates/mutatingwebhook.yaml#L24)). Webhook definitions do not support a logical OR, so the solution would be to add another webhook.
We tried this and encountered the following problem: an injector pod can only get one webhook at a time and therefore doesn't add the necessary caBundle entry to the second webhook configuration (see [sidecar-injector/main.go](https://github.com/istio/istio/blob/b8e30e07ec7b36cf1ba1b445b78c81fdf0d417b9/pilot/cmd/sidecar-injector/main.go)).

We have two ideas how to fix this problem but are unsure which one to choose:

- change the behaviour of the sidecar-injector to allow more than one webhook. This has the disadvantage that the fix might only enter istio 1.2 (or later) and it would not be available for now
- create a second sidecar-injector pod in the default istio-control namespace to provide the second webhook if enableNamespacesByDefault is set. Obviously the disadvantage here is that one would have two pods doing exactly the same

If neither fix is implemented we should add a warning in the documentation. We would be happy to help with implementation of one of the proposed solutions.

**Comment by costinm** [comment] 2019-03-15 20:50
I'm not sure what is the problem - if enableNamespacesByDefault is set, all namespaces without a label will be injected. User is not supposed to set a label unless they want to override - and I think this part works. 

I agree it's tricky to make it work if you have the istio-env set to the 'default', but is it a major problem ? 

I think the second option is already doable - if user has istio-env=istio-control and decide they want to have 'enableNamespacesByDefault' they can create a new environment with that setting, and leave
istio-control as is. This is effectively creating a second sidecar injector pod - but not in istio-control namespace. That's the only difference compared with your second proposal.

**Comment by phil9909** [comment] 2019-03-18 09:07
Just to make sure we are on the same page: The problem is not setting it to 'default', rather setting it explicitly to the default namespace. For example if one has two istio instances configured like in the README (`istio-control` with `enableNamespacesByDefault=true` and `istio-master`), the autoinjector would inject a sidecar if:
-  the given namespace has no `istio-env` label
-  the given namespace has `istio-env=istio-master`

But not for namespaces with the label `istio-env=istio-control`.

> I agree it's tricky to make it work if you have the istio-env set to the 'default', but is it a major problem ?

I don't think it is a major problem, but it could be good to have it documented. Especially for future scenarios where you want to switch the default environment during migrations. E.g., if a namespace has `istio-env` explicitly set to `namespace0` and `namespace0` now becomes the default, this would be an issue.

**Comment by costinm** [comment] 2019-03-20 00:31
I thought about it a bit more - I really want to avoid making the selection more complex, in particular considering CNI will eventually replace injector - and it will also need to play nicely with the new installer. 
The namespace label was a good solution to get things working - but I'm not sure this is the best long term  solution.

How about: we can document that if a user wants to have 'default' injection, there is a single namespace where this can be defined - say "istio-sidecar-default". That namespace will run only the sidecar injector, nothing else - it can point to pilot in istio-control. User can change that to point to istio-1.2 or istio-1.3 or istio-canary or whatever control namespace he wants.

Long term: I think we can try moving the 'environment' into the Sidecar API - maybe by using the egress
section - for example you define 'istio-pilot.istio-master'. The injector will need to watch MCP or ask pilot
for the proper config to use. 

Eventually - CNI will take over, and CNI is by definition a singleton, like citadel. We don't want to have multiple CNIs instances. We can do the same for the injector - a single injector running, but with the template customized.

Another simple fix to injector would be to change it a bit to allow multiple 'templates' to be used, so you can have a singleton injector but using different 'templates' based on pod annotations or namespace label.  

But short term - I would just document this limitation about default.

**Comment by loewenstein** [comment] 2019-03-20 14:43
> But short term - I would just document this limitation about default.

Agreed. Documenting that setting `enableNamespacesByDefault` and `istio-env=<istio namespace>` can lead to surprising results should be enough for the short term.

> Long term: I think we can try moving the ‘environment’ into the Sidecar API - maybe by using the egress section - for example you define ‘istio-pilot.istio-master’. The injector will need to watch MCP or ask pilot for the proper config to use.

Using the Sidecar resource sounds appealing. It would allow to configure global defaults, namespace defaults as well as workload specific Istio control plane configuration, correct? Actually it could replace the `enableNamespacesByDefault` setting as well, right?
However, I think 're-using' the egress listener gets a bit too implicit. What about an extra field as sibling to 'workloadSelector', 'ingress' and 'egress'? Maybe 'controlPlane' or 'pilot'?

> Eventually - CNI will take over, and CNI is by definition a singleton, like citadel. We don't want to have multiple CNIs instances. We can do the same for the injector - a single injector running, but with the template customized.

I am not sure I like the idea of an additional singleton. If there is a good reason to canary _any_ Istio component, I suppose there is a good reason to canary _all_ of them.

**Comment by costinm** [comment] 2019-03-20 18:31
We can add an explicit section. We already have an annotation for pods that allows selecting a specific 
pilot URL ( used in the istio/tools perf cluster for example ), and we can go down to per-pod selection of the environment and injection mechanism. The annotation is visible in sidecar injector. 

Regarding 'singleton' - we should be pragmatic. Sidecar injector can be canaried with the current solution, the only problem is the '*', having 2 sidecars with * is undeterministic and dangerous. 
I think having a singleton injector for 'default' is not so bad.

**Comment by loewenstein** [comment] 2019-03-20 19:06
> We can add an explicit section. We already have an annotation for pods that allows selecting a specific pilot URL ( used in the istio/tools perf cluster for example ), and we can go down to per-pod selection of the environment and injection mechanism. The annotation is visible in sidecar injector.

So, should we go the Sidecar resource route or are you proposing to stick to the annotations?
In the former case I might try to sketch a use case (like gradual control plane update) as an issue to reference for a change of the Sidecar API and the Injector implementations currently working on annotations and labels. This would be backwards incompatible... Do we have to keep old mechanisms for at least 1.2?

> Regarding 'singleton' - we should be pragmatic. Sidecar injector can be canaried with the current solution, the only problem is the '*', having 2 sidecars with * is undeterministic and dangerous.
I think having a singleton injector for 'default' is not so bad.

Sure, the 'default' injector will be a singleton (meaning only one can be configured to act as default), no matter if it is the classical sidecar injector or the future CNI plugin. However, I suppose for being able to canary the injection via CNI we will need to support multiple CNI DaemonSets at any given point in time. Of course they have to be configured, so that only one CNI plugin acts on any given workload.

**Comment by costinm** [comment] 2019-04-05 18:58
I think we can close this - we may have additional refactoring in the injector, to better align with CNI, and make further improvements and add more flexibility in code. 
Until it happens - I think we can keep the current solution.

**Closed by costinm** 2019-04-05 18:58 UTC
